version: "3"

services:
  chatgpt-api-server:
    build: .
    ports:
      - "8080:8080"
    command: ["ChatGPT-API-server", "8080", "<API_KEY>", "-listen", "0.0.0.0"]
    networks:
      - chatgpt-api-server_default

networks:
  chatgpt-api-server_default:

